# Generated by Django 2.2 on 2019-04-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozlucka', '0002_auto_20190423_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
