# Generated by Django 2.2 on 2019-04-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rozlucka', '0004_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozlucka.Puzzle')),
            ],
        ),
    ]
