# Generated by Django 2.2 on 2019-04-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozlucka', '0005_answerattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerattempt',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
