# Generated by Django 2.2 on 2019-04-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rozlucka', '0006_answerattempt_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerattempt',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='rozlucka.Puzzle'),
        ),
    ]
