# Generated by Django 2.2 on 2019-04-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rozlucka', '0011_stationfacilitatorguess'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationfacilitatorguess',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stationfacilitator',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitators', to='rozlucka.Station'),
        ),
        migrations.AlterField(
            model_name='stationfacilitatorguess',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_guesses', to='rozlucka.Station'),
        ),
    ]
