# Generated by Django 2.2 on 2019-04-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rozlucka', '0012_auto_20190425_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationfacilitatorguess',
            old_name='name',
            new_name='text',
        ),
    ]
