# Generated by Django 2.2 on 2019-04-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozlucka', '0013_auto_20190426_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
