# Generated by Django 2.2 on 2019-04-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozlucka', '0014_station_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
