---
- name: Setup all my servers on AWS
  hosts: web
  vars:
    django_archive: dist/rozlucka-{{ lookup("env", "PACKAGE_VERSION") }}.tar.gz
    django_config_file: local_settings.j2
    django_config: api.settings
    django_project_name: 'cz-zak-global-rozlucka'
    django_project_environment: '{{ lookup("env", "DJANGO_PROJECT_ENVIRONMENT") }}'
    django_wsgi_file: api/wsgi.py

  roles:
    - role: practical-ansible.nginx-django
